Fix links to experimental template API docs
watsonwork/watsonwork-developer-docs pull request #114
Opened 2018-09-13 22:47 UTC by AlanGreene

Links to 'Get team templates' and 'Share space template' should be pointing to GitHub.com as these APIs are still experimental.

2018-09-13 22:49 UTC, AlanGreene commented
@miguelestrada please review

2018-09-13 23:08 UTC, miguelestrada requested changes
Would it be possible to also fix the other links in the same section?  They should not be to the md files but rather to the actual entries from navigation section.  If you want to treat as separate PR that is fine too.  Let me know and I can merge this one first.

2018-09-14 09:13 UTC, AlanGreene commented
The links to the .md files are transformed in the DX build to use the slugs from the metadata as long as it recognises the path, e.g. links to docs in the 'guides' section must include 'guides' in the path. Same pattern in use in other docs.

Verified with a local DX build consuming this branch
![image](https://user-images.githubusercontent.com/2829095/45541333-ba513980-b806-11e8-95b2-3de01cdb044c.png)

2018-09-17 16:52 UTC, AlanGreene commented
@miguelestrada can this be merged?

2018-09-17 19:12 UTC, miguelestrada approved these changes

2018-09-17 19:12 UTC, merged