Submit App Catalog Guide
watsonwork/watsonwork-developer-docs pull request #45
Opened 2018-02-27 19:41 UTC by jarusso

2018-02-27 20:00 UTC, jarusso commented
@miguelestrada please review and merge

2018-03-05 15:45 UTC, miguelestrada requested changes

2018-03-05 15:45 UTC, miguelestrada commented on guides/V1_PublishInTheCatalog.md
> +When you do that, it will appear on the Apps page for every person using Watson Workspace. They can then get your app and
Replace:

>When you do that, it will appear on the Apps page for every person using Watson Workspace. They can then get your app and starting enjoying your hard work

with:

When you do that, your app will be exposed to users of applications based on Work Services via their presentation of the Catalog.  For example, IBM Watson Workspace presents the catalog in the Apps section of a space settings page.  Note that in some cases involving paid organizations administrators may still block your app from being displayed as they can pick and choose which apps are utilized.

2018-03-05 15:45 UTC, miguelestrada commented on guides/V1_PublishInTheCatalog.md
> +For your app to get into the catalog, you have to Submit it for review. You can do this by going to
> For your app to get into the catalog, you have to Submit it for review. You can do this by going to

to:

For your app to get into the catalog, you have to first Submit it for review by IBM. You can do this by going to

2018-03-06 14:26 UTC, jarusso commented on guides/V1_PublishInTheCatalog.md
> +When you do that, it will appear on the Apps page for every person using Watson Workspace. They can then get your app and
done

2018-03-06 14:27 UTC, jarusso commented on guides/V1_PublishInTheCatalog.md
> +For your app to get into the catalog, you have to Submit it for review. You can do this by going to
done

2018-03-06 14:28 UTC, jarusso commented
all changes made, please re-review and merge @miguelestrada

2018-03-06 18:02 UTC, miguelestrada approved these changes

2018-03-06 18:02 UTC, merged