Add space updated and deleted webhook doc
watsonwork/watsonwork-developer-docs pull request #59
Opened 2018-03-26 15:58 UTC by trik-1

@miguelestrada @jarusso Could I get a review please ?

Corresponding internal discussion 33252 32787
Corresponding internal tickets 33201, 33199

2018-03-26 16:11 UTC, AlanGreene requested changes

2018-03-26 16:11 UTC, AlanGreene commented on references/V1_OutboundCallback.md
> +- have been added for the message-updated event
`space-updated` ?

2018-03-26 16:11 UTC, AlanGreene commented on references/V1_OutboundCallback.md
> +|**description**  <br>*optional*|The new title of the space.|string|
`The new description of the space.`

2018-03-26 16:11 UTC, AlanGreene commented on references/V1_OutboundCallback.md
> +<a name="spaceupdatedbody"></a>
`spacedeletedbody`

2018-03-26 16:11 UTC, AlanGreene commented on references/V1_OutboundCallback.md
> +- have been added for the message-deleted event
`space-deleted`

2018-03-26 16:24 UTC, jarusso commented
@trik-1 looks good - but need you to also make an entry in the What's New md file about this change/update

2018-03-28 13:46 UTC, trik-1 commented
@jarusso could I get another once over please ?

2018-03-29 08:20 UTC, miguelestrada approved these changes

2018-03-29 13:53 UTC, trik-1 commented
@miguelestrada Missed out on one small part added in last commit. Should be ready to merge.

2018-03-29 17:12 UTC, merged