Update Coming_Next.md
watsonwork/watsonwork-developer-docs pull request #62
Opened 2018-04-04 14:26 UTC by jarusso

2018-04-04 14:28 UTC, jarusso commented
@miguelestrada review and merge please

2018-04-04 20:17 UTC, miguelestrada requested changes

2018-04-04 20:17 UTC, miguelestrada commented on Coming_Next.md
> +| **Templates.** We're adding **Templates** for you to create custom experiences for teams. It's `EXPERIMENTAL` but you can check it out here, [Space Template](https://github.com/watsonwork/watsonwor
@jarusso here is the main info doc for templates.  Can we link to it as first link?
https://github.com/watsonwork/watsonwork-developer-docs/blob/master/guides/V1_space_template_main.md

2018-04-04 20:17 UTC, miguelestrada commented on Coming_Next.md
> +| **Templates.** We're adding **Templates** for you to create custom experiences for teams. It's `EXPERIMENTAL` but you can check it out here, [Space Template](https://github.com/watsonwork/watsonwor
If you want the complete list to be displayed in the `Coming Next` section then this one should be included as well:

https://github.com/watsonwork/watsonwork-developer-docs/blob/master/guides/V1_get_offering_space_templates.md

2018-04-04 20:40 UTC, jarusso commented
@miguelestrada changes made

2018-04-05 10:07 UTC, miguelestrada commented on Coming_Next.md
> +| **Templates.** We're adding **Templates** for you to create custom experiences for teams. It's `EXPERIMENTAL` but you can check it out here, [Space Template](https://github.com/watsonwork/watsonwor
Missing one.
https://github.com/watsonwork/watsonwork-developer-docs/blob/master/guides/V1_get_my_space_templates.md

2018-04-05 10:07 UTC, miguelestrada requested changes
https://github.com/watsonwork/watsonwork-developer-docs/blob/master/guides/V1_get_my_space_templates.md

2018-04-05 16:18 UTC, jarusso commented
good catch, fixed that item @miguelestrada

2018-04-05 17:17 UTC, miguelestrada requested changes

2018-04-05 17:17 UTC, miguelestrada commented on Coming_Next.md
> +| **Templates.** We're adding **Templates** for you to create custom experiences for teams. It's `EXPERIMENTAL` but you can check it out here, [Space Template](https://github.com/watsonwork/watsonwor
One minor thing.... can we pluralize this?  It returns a collection not a template....  it is the analog to getting a list of all the apps you have created.... but for templates...  

>Get My Space Template

to

>Get My Space Templates

2018-04-05 18:13 UTC, miguelestrada approved these changes

2018-04-05 18:13 UTC, merged