[Ready after merge of pull 98] Graduate reactions graphQL API to public
watsonwork/watsonwork-developer-docs pull request #97
Opened 2018-07-11 13:37 UTC by pjoviak

Issue: [https://github.ibm.com/toscana/planning/issues/36710](https://github.ibm.com/toscana/planning/issues/36710)
Graduate reactions graphQL API to public.

2018-07-11 14:40 UTC, pjoviak commented
@miguelestrada @jarusso @roy713 Please review.  Thank you.

2018-07-11 14:45 UTC, roy713 commented on Coming_Next.md
> +copyright: 'Copyright IBM Corp. 2017,2018'
Very minor but should we add a space?

2018-07-11 14:45 UTC, roy713 commented on Whats_New.md
> +| 06.Jul.2018   | Added sections for [message editing](https://github.com/watsonwork/watsonwork-developer-docs/blob/master/guides/V1_wwsg_EditingMessages.md) as `experimental`. |
Should we have experimental all caps?

2018-07-11 14:45 UTC, roy713 commented on guides/V1_message_main.md
> +| reactions | [Reaction] | A set of optional objects that are added to a message, called reactions. Each reaction represents how users reacted to the message. A Reaction is represented by the reactio
Should we decorate reaction, count, viewerHasReacted? I don't know what the standard in the docs is so...

2018-07-11 15:58 UTC, roy713 approved these changes

2018-07-12 11:54 UTC, pjoviak commented
@miguelestrada @jarusso Could you please guardian review, when you get a chance ?
Thank you.

2018-07-12 15:06 UTC, miguelestrada requested changes
@jarusso see my comments here.

2018-07-12 15:06 UTC, miguelestrada commented on Coming_Next.md
> +| **Editing a Message.** It's `EXPERIMENTAL` but you can check it out here, [Editing Messages](https://github.com/watsonwork/watsonwork-developer-docs/blob/master/guides/V1_wwsg_EditingMessages.md).
I think this should be separate PR (edit message API)
Actually even the graduation of Reaction and Delete message to public should be 2 separate ones, but will continue this review regardless.

2018-07-12 15:06 UTC, miguelestrada commented on NavigationMenu.md
> +  * [Optional inclusion of soft deleted flag with message retrieval](./guides/V1_message_main.md)
Too long of a navigation title? @jarusso

2018-07-12 15:06 UTC, miguelestrada commented on NavigationMenu.md
> +  * [Events for message deletion (message-deleted)](./guides/V1_wwsg_Webhooks.md)
Are we going to have a section for events related to each object or do we keep all events in one place @jarusso

2018-07-12 15:06 UTC, miguelestrada commented on guides/V1_message_main.md
> +| contentUpdated | Date | Date this message content was edited or null. Available when you add `EXPERIMENTAL` to the `x-graphql-view` header |
Related to update message work

2018-07-13 11:53 UTC, pjoviak commented
@jarusso Comments?  @miguelestrada  Do you need this split this into multiple PRs?
Thank you.

2018-07-14 12:28 UTC, miguelestrada commented on NavigationMenu.md
> +* ## [Reactions](./guides/V1_wwsg_Reactions.md)
@pjoviak @jarusso so this reactions stuff is all related to messages and wondering if it should be inside the message section as well?

2018-07-14 12:30 UTC, miguelestrada commented
@pjoviak  I think breaking it up should help speed up the delivery.  The 3 PRs would be:
1. Reactions
2. Delete Message
3. Update Message

@jarusso FYI

2018-07-19 20:52 UTC, miguelestrada approved these changes

2018-07-19 21:05 UTC, merged